import "dotenv/config";
// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations"
  },
  datasource: {
    url: process.env.DATABASE_URL ||
      "postgres://d2570495de363aa7b2068e2c74d9e4dd1cce2722f966d7496f06bb6dd802013c:sk_pL0qO5nMqaRiSiulUVewI@db.prisma.io:5432/postgres?sslmode=require",
  },
});
